name = "chord-detective"
main = "_worker.js"
compatibility_date = "2025-01-01"

[assets]
directory = "."
not_found_handling = "single-page-application"
html_handling = "auto-trailing-slash"

[[headers]]
for = "/*"
[headers.values]
Cross-Origin-Opener-Policy = "same-origin"
Cross-Origin-Embedder-Policy = "require-corp"
